export const prints = [
  {
    id: 1,
    name: "Summer Stripes n°6 - original",
    price: 100,
    status: "Available",
    image: "/test.jpg",
    description:
      "Created using acrylic paint on canvas with a palette knife and brush.",
    size: "30x40cm",
    quantity: 1,
    totalQuantity: 2,
  },
  {
    id: 2,
    name: "Painting 2",
    price: 120,
    status: "Sold",
    image: "/test2.jpg",
    description:
      "Created using acrylic paint on canvas with a palette knife and brush.",
    size: "30x40cm",
    quantity: 0,
    totalQuantity: 0,
  },
  {
    id: 3,
    name: "Painting 3",
    price: 100,
    status: "Available",
    image: "/test3.jpg",
    description:
      "Created using acrylic paint on canvas with a palette knife and brush.",
    size: "30x40cm",
    quantity: 2,
    totalQuantity: 2,
  },
  {
    id: 4,
    name: "Painting 4",
    price: 120,
    status: "Available",
    image: "/test2.jpg",
    description:
      "Created using acrylic paint on canvas with a palette knife and brush.",
    size: "30x40cm",
    quantity: 1,
    totalQuantity: 2,
  },
  {
    id: 5,
    name: "Painting 5",
    price: 100,
    status: "Available",
    image: "/test.jpg",
    description:
      "Created using acrylic paint on canvas with a palette knife and brush.",
    size: "30x40cm",
    quantity: 2,
    totalQuantity: 5,
  },
  {
    id: 6,
    name: "Painting 6",
    price: 100,
    status: "Available",
    image: "/test2.jpg",
    description:
      "Created using acrylic paint on canvas with a palette knife and brush.",
    size: "30x40cm",
    quantity: 4,
    totalQuantity: 4,
  },
  {
    id: 7,
    name: "Painting 7",
    price: 120,
    status: "Sold",
    image: "/test3.jpg",
    description:
      "Created using acrylic paint on canvas with a palette knife and brush.",
    size: "30x40cm",
    quantity: 0,
    totalQuantity: 0,
  },
  {
    id: 8,
    name: "Painting 8",
    price: 120,
    status: "Sold",
    image: "/test3.jpg",
    description:
      "Created using acrylic paint on canvas with a palette knife and brush.",
    size: "30x40cm",
    quantity: 0,
    totalQuantity: 0,
  },
  {
    id: 9,
    name: "Painting 9",
    price: 100,
    status: "Available",
    image: "/test.jpg",
    description:
      "Created using acrylic paint on canvas with a palette knife and brush.",
    size: "30x40cm",
    quantity: 1,
    totalQuantity: 2,
  },
];
