import Footer from "@/components/Footer";
import "./globals.css";
import Navbar from "@/components/Navbar";
import GlobalState from "./context/page";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <GlobalState>
          <Navbar />
          {children}
          <Footer />
        </GlobalState>
      </body>
    </html>
  );
}
